services:

  postgres:
    image: postgres:17
    container_name: taskflow-postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5433:5432"

    volumes:
      - taskflow-postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U taskflow -d taskflow_docker" ]
      interval: 5s
      timeout: 5s
      retries: 5

  taskflow:
    build: .
    container_name: taskflow-api

    environment:
      DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}

    ports:
      - "8080:8080"

    depends_on:
      postgres:
          condition: service_healthy

volumes:
  taskflow-postgres-data:
    external: true