spring.application.name=TaskFlow

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/taskflow_docker}
spring.datasource.username=${DB_USERNAME:taskflow}
spring.datasource.password=${DB_PASSWORD:taskflow123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}

##*spring.jpa.open-in-view=false*##